Ansible 1
Otus-DevOps-2022-05/IngvarrRnD_infra pull request #7
Opened 2022-07-17 15:11 UTC by IngvarrRnD

# Выполнено ДЗ № 8

 - [+] Основное ДЗ
 - [+] Задание со *

## В процессе сделано:
1) Создана плейбука clone.yml, в которой выполняется копирования файлов из репозитория
Плейбука была доработана с моей стороны, т.к. на удаленной машине не был установлен git
2) Создание динамического инвентори

С помощью bash скрипта выполняем генерацию инвентори, путем получаения данных через апи яндекс клауд, затем парся ответ и генерируя json

Пример вывода

 ansible-inventory --inventory 2.sh --list
{
    "_meta": {
        "hostvars": {
            "62.84.115.208": {
                "hostname": [
                    "bastion"
                ]
            },
            "62.84.117.51": {
                "hostname": [
                    "reddit-app"
                ]
            },
            "62.84.119.70": {
                "hostname": [
                    "reddit-db"
                ]
            }
        }
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    },
    "ungrouped": {
        "hosts": [
            "62.84.115.208",
            "62.84.117.51",
            "62.84.119.70"
        ]
    }
}

Пример запуска модуля ping

Таск по хосу bastion не выполнился, т.к. на нем иной ssh ключ прокинут

ansible --inventory 2.sh -m ping all
62.84.115.208 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '62.84.115.208' (ECDSA) to the list of known hosts.\r\nubuntu@62.84.115.208: Permission denied (publickey).",
    "unreachable": true
}
62.84.119.70 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
62.84.117.51 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-07-17 15:14 UTC, IngvarrRnD commented
традиционно не проходит обходное решение для terraform

2022-07-18 13:45 UTC, mrgreyves requested changes
Здравствуйте!)
Да, с терраформом вы правы
Так же не хватает файла инвентаря inventory.yml
Приключение на 10 минут =)
Давайте поправим =)

2022-07-31 16:32 UTC, IngvarrRnD commented
Выпал на 2 недели из-за работы  перед отпуском и на время самого отпуска (
файл inventory был, без расширения yml только
добавил расширение

2022-08-01 10:18 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
Перед мержем внесите мелкие правки на которые указывают тесты
ДЗ принимаю =)

2022-08-01 16:36 UTC, merged